/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    RubberDuckBeak_RubberDuckBeak_0: THREE.Mesh
    RubberDuckBody_RubberDuck_0: THREE.Mesh
    RubberDuckEyes_RubberDuckEyeBlack_0: THREE.Mesh
    RubberDuckEyes_RubberDuckEyeWhite_0: THREE.Mesh
    Lamp_lambert1_0: THREE.Mesh
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4001: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6001: THREE.Mesh
    Object_7001: THREE.Mesh
    Object_8001: THREE.Mesh
    Cube_Black_0: THREE.Mesh
    Cube_Blue_0: THREE.Mesh
    Cube_Green_0: THREE.Mesh
    Cube_Orange_0: THREE.Mesh
    Cube_Red_0: THREE.Mesh
    Cube_White_0: THREE.Mesh
    Cube_Yellow_0: THREE.Mesh
    Object_6002: THREE.Mesh
    Object_8002: THREE.Mesh
    Object_4003: THREE.Mesh
    Cube_BookColor_0: THREE.Mesh
    Cube_White_0001: THREE.Mesh
    Cylinder396_brown_0: THREE.Mesh
    Cylinder397_brown_0: THREE.Mesh
    Cylinder398_brown_0: THREE.Mesh
    Cylinder399_black_0: THREE.Mesh
    Cylinder400_black_0: THREE.Mesh
    Cylinder400_L_yellow_0: THREE.Mesh
    Cylinder400_white_0: THREE.Mesh
    Rectangle001_black_0: THREE.Mesh
    pCube1_Flat_Wood_1_0: THREE.Mesh
    pCube2_Flat_Wood_1_0: THREE.Mesh
    pCube3_Flat_Wood_1_0: THREE.Mesh
    pCube4_Flat_Wood_1_0: THREE.Mesh
    pCylinder1_Flat_Wood_1_0: THREE.Mesh
    Phone: THREE.Mesh
    Floor: THREE.Mesh
    ['Monitor+box']: THREE.Mesh
    Keyboard: THREE.Mesh
    Mouse: THREE.Mesh
    screen: THREE.Mesh
    Foot_right_front: THREE.Mesh
    Foot_right_back: THREE.Mesh
    Foot_left_front: THREE.Mesh
    Foot_left_back: THREE.Mesh
    Desk_plot: THREE.Mesh
    Frame: THREE.Mesh
    pic: THREE.Mesh
  }
  materials: {
    RubberDuckBeak: THREE.MeshStandardMaterial
    RubberDuck: THREE.MeshStandardMaterial
    RubberDuckEyeBlack: THREE.MeshStandardMaterial
    RubberDuckEyeWhite: THREE.MeshStandardMaterial
    ['lambert1.001']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    Orange: THREE.MeshStandardMaterial
    ['material.001']: THREE.MeshStandardMaterial
    ['White.001']: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    PRETOl: THREE.MeshStandardMaterial
    branco1: THREE.MeshStandardMaterial
    BookColor: THREE.MeshStandardMaterial
    ['White.002']: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    L_yellow: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    Flat_Wood_1: THREE.MeshStandardMaterial
    Mat: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    pic: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/desk.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.81, 2.39, -0.64]} rotation={[-Math.PI / 2, 0, 0.41]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[144.44, 197.95, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={129.89}>
            <mesh geometry={nodes.RubberDuckBeak_RubberDuckBeak_0.geometry} material={materials.RubberDuckBeak} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.RubberDuckBody_RubberDuck_0.geometry} material={materials.RubberDuck} />
          </group>
          <group position={[153.03, 193.69, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={129.89}>
            <mesh geometry={nodes.RubberDuckEyes_RubberDuckEyeBlack_0.geometry} material={materials.RubberDuckEyeBlack} />
            <mesh geometry={nodes.RubberDuckEyes_RubberDuckEyeWhite_0.geometry} material={materials.RubberDuckEyeWhite} />
          </group>
        </group>
      </group>
      <group position={[0.84, 3.26, -2.89]} rotation={[-Math.PI / 2, 0, -0.18]} scale={1.35}>
        <group rotation={[Math.PI / 2, -0.18, 0]} scale={0.01}>
          <group rotation={[0, -0.18, 0]}>
            <group position={[58.91, 0, -26.62]} rotation={[0, -0.18, 0]}>
              <mesh geometry={nodes.Lamp_lambert1_0.geometry} material={materials['lambert1.001']} position={[-28.66, 0, -33.97]} rotation={[0, 0.04, 0]} />
            </group>
          </group>
        </group>
      </group>
      <group position={[0.75, 2.34, -2.2]} rotation={[-Math.PI / 2, 0, 1.96]} scale={0.02}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_4001.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_6001.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_7001.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_8001.geometry} material={materials['Material.011']} />
      </group>
      <group position={[-0.26, 2.29, -2.54]} rotation={[-Math.PI / 2, 0, 0.35]} scale={0.13}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[818.19, 536.56, -810.92]} rotation={[-Math.PI, -0.79, 2.86]} />
          <group position={[0, 138.73, 19.11]}>
            <mesh geometry={nodes.Cube_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Cube_Blue_0.geometry} material={materials.Blue} />
            <mesh geometry={nodes.Cube_Green_0.geometry} material={materials.Green} />
            <mesh geometry={nodes.Cube_Orange_0.geometry} material={materials.Orange} />
            <mesh geometry={nodes.Cube_Red_0.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.Cube_White_0.geometry} material={materials['White.001']} />
            <mesh geometry={nodes.Cube_Yellow_0.geometry} material={materials.Yellow} />
          </group>
        </group>
      </group>
      <group position={[0, 2.33, 1.9]} rotation={[-Math.PI / 2, 0, -0.26]} scale={0.11}>
        <group rotation={[0, 0, 0.57]}>
          <group rotation={[Math.PI / 2, 0.57, 0]}>
            <group position={[0.08, 2.17, 0.65]} rotation={[-0.01, -0.89, -0.04]} scale={0.99}>
              <mesh geometry={nodes.Object_6002.geometry} material={materials['Material.013']} rotation={[-0.02, 0.57, 0.01]} />
            </group>
            <group position={[0.06, 0, 0.57]} rotation={[-0.01, -0.89, -0.04]}>
              <mesh geometry={nodes.Object_8002.geometry} material={materials.PRETOl} rotation={[-0.02, 0.57, 0.01]} />
            </group>
            <group position={[0.06, 0, 0.57]} rotation={[-0.01, -0.89, -0.04]}>
              <mesh geometry={nodes.Object_4003.geometry} material={materials.branco1} rotation={[-0.02, 0.57, 0.01]} />
            </group>
          </group>
        </group>
      </group>
      <group position={[0.51, 2.43, -3.03]} rotation={[-3.14, -1.28, 1.57]} scale={13.97}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.59, 2.18, 2.96]}>
            <mesh geometry={nodes.Cube_BookColor_0.geometry} material={materials.BookColor} />
            <mesh geometry={nodes.Cube_White_0001.geometry} material={materials['White.002']} />
          </group>
        </group>
      </group>
      <group position={[-1.75, 0, 2.42]} rotation={[-Math.PI / 2, 0, -2.5]} scale={0.04}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[39.4, 0, -30.87]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[4.78, 0, 0]} rotation={[0, -0.17, 0]}>
              <group position={[22.14, 0, -3.69]}>
                <mesh geometry={nodes.Cylinder396_brown_0.geometry} material={materials.brown} />
              </group>
            </group>
            <group position={[4.4, -0.22, 0]} rotation={[-0.15, 0.09, -2.09]}>
              <group position={[22.14, 0, -3.69]}>
                <mesh geometry={nodes.Cylinder397_brown_0.geometry} material={materials.brown} />
              </group>
            </group>
            <group position={[4.4, 0.22, 0]} rotation={[0.15, 0.09, 2.09]}>
              <group position={[22.14, 0, -3.69]}>
                <mesh geometry={nodes.Cylinder398_brown_0.geometry} material={materials.brown} />
              </group>
            </group>
            <group position={[4.55, -0.02, 0]} scale={[0.45, 0.45, 1]}>
              <group position={[0, 0, 116.96]}>
                <mesh geometry={nodes.Cylinder399_black_0.geometry} material={materials.black} />
              </group>
            </group>
            <group position={[4.55, 2.23, 0]} rotation={[Math.PI / 2, 0, Math.PI / 6]}>
              <group position={[69.31, 120.05, 0]}>
                <mesh geometry={nodes.Cylinder400_black_0.geometry} material={materials.black} />
                <mesh geometry={nodes.Cylinder400_L_yellow_0.geometry} material={materials.L_yellow} />
                <mesh geometry={nodes.Cylinder400_white_0.geometry} material={materials.white} />
              </group>
            </group>
            <group position={[4.54, -0.05, 0]} rotation={[0, -1.57, 0]}>
              <group position={[133.67, 0, 0]}>
                <mesh geometry={nodes.Rectangle001_black_0.geometry} material={materials.black} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[1.48, 0.2, 0.91]} rotation={[-Math.PI / 2, 0, -1.44]} scale={0.25}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.99, 2.4, -1.22]} scale={[0.61, 5.13, 0.61]}>
            <mesh geometry={nodes.pCube1_Flat_Wood_1_0.geometry} material={materials.Flat_Wood_1} />
          </group>
          <group position={[-1.41, 2.52, 1.37]} rotation={[0, 0.1, 0]} scale={[0.61, 5.13, 0.61]}>
            <mesh geometry={nodes.pCube2_Flat_Wood_1_0.geometry} material={materials.Flat_Wood_1} />
          </group>
          <group position={[1.31, 2.52, 1.6]} rotation={[0, 0.13, 0]} scale={[0.61, 5.13, 0.61]}>
            <mesh geometry={nodes.pCube3_Flat_Wood_1_0.geometry} material={materials.Flat_Wood_1} />
          </group>
          <group position={[1.33, 2.52, -1.31]} rotation={[0, -0.1, 0]} scale={[0.61, 5.13, 0.61]}>
            <mesh geometry={nodes.pCube4_Flat_Wood_1_0.geometry} material={materials.Flat_Wood_1} />
          </group>
          <group position={[0, 5.16, 0]} scale={[2.88, 0.14, 2.88]}>
            <mesh geometry={nodes.pCylinder1_Flat_Wood_1_0.geometry} material={materials.Flat_Wood_1} />
          </group>
        </group>
      </group>
    //DESK LAMP
      <pointLight intensity={0.6134} decay={2} color="#00a5ff" position={[-0.42, 3.49, -2.78]} rotation={[-Math.PI / 2, 0, 0]} />
    //RED LIGHT
      <spotLight intensity={0.439} angle={0.98} penumbra={0.15} decay={2} color="#ff0000" position={[-1.83, 5.2, 3.8]} rotation={[-0.87, -0.8, 0.31]} />
    //WARM ABOVE DESK
      <pointLight intensity={0.920} decay={2} color="#ff9500" position={[1.14, 5.04, 0.2]} rotation={[-1.72, 1.02, 0.12]} />
    //BLUE ABOVE DESK
      <pointLight intensity={0.620} decay={2} color="#0004ff" position={[-0.97, 4.99, -3.06]} rotation={[-1.72, 1.02, 0.12]} />
    //WARM VIEWER POINT
      <pointLight intensity={0.425} decay={2} color="#ffc000" position={[9.39, 7.38, 3.12]} rotation={[-1.03, 1.15, -0.59]} />
    //PICTURE
      <pointLight intensity={0.30} decay={2} position={[-0.51, 2.74, -1.04]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Phone.geometry} material={materials.Mat} position={[-0.81, 2.33, -1.94]} scale={0.01} />
      <mesh geometry={nodes.Floor.geometry} material={materials['Material.002']} position={[0.69, 0.22, 0.13]} scale={25.64} />
      <mesh geometry={nodes['Monitor+box'].geometry} material={materials.Material} position={[-0.17, 0, 1.05]} />
      <mesh geometry={nodes.Keyboard.geometry} material={materials.Material} position={[0, 0, 1.05]} />
      <mesh geometry={nodes.Mouse.geometry} material={materials.Material} position={[0, 0, 1.05]} />
      <mesh geometry={nodes.screen.geometry} material={materials.screen} position={[-0.62, 3.37, 0.85]} rotation={[Math.PI / 2, 0, -1.57]} scale={[1.22, 1.05, 1.01]} />
      <mesh geometry={nodes.Foot_right_front.geometry} material={materials.Material} position={[0.2, 0, -1]} />
      <mesh geometry={nodes.Foot_right_back.geometry} material={materials.Material} position={[-0.2, 0, -1]} />
      <mesh geometry={nodes.Foot_left_front.geometry} material={materials.Material} position={[0.2, 0, 1]} />
      <mesh geometry={nodes.Foot_left_back.geometry} material={materials.Material} position={[-0.2, 0, 1]} />
      <mesh geometry={nodes.Desk_plot.geometry} material={materials['Material.003']} position={[-0.09, 2.21, -0.06]} rotation={[0, 0, -Math.PI]} scale={[-1.4, -0.13, -3.69]} />
      <mesh geometry={nodes.Frame.geometry} material={materials.Material} position={[0, 0, 1.05]} />
      <mesh geometry={nodes.pic.geometry} material={materials.pic} position={[-0.65, 2.68, -1.12]} rotation={[1.51, 0.16, -1.21]} scale={0.55} />
    </group>
  )
}

useGLTF.preload('/desk.glb')
