/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { Dispatch, SetStateAction, useRef } from 'react';
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Props, useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    RubberDuckBeak_RubberDuckBeak_0: THREE.Mesh;
    RubberDuckBody_RubberDuck_0: THREE.Mesh;
    RubberDuckEyes_RubberDuckEyeBlack_0: THREE.Mesh;
    RubberDuckEyes_RubberDuckEyeWhite_0: THREE.Mesh;
    Lamp_lambert1_0: THREE.Mesh;
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4001: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6001: THREE.Mesh;
    Object_7001: THREE.Mesh;
    Object_8001: THREE.Mesh;
    Cube_Black_0: THREE.Mesh;
    Cube_Blue_0: THREE.Mesh;
    Cube_Green_0: THREE.Mesh;
    Cube_Orange_0: THREE.Mesh;
    Cube_Red_0: THREE.Mesh;
    Cube_White_0: THREE.Mesh;
    Cube_Yellow_0: THREE.Mesh;
    Object_6002: THREE.Mesh;
    Object_8002: THREE.Mesh;
    Object_4003: THREE.Mesh;
    Cube_BookColor_0: THREE.Mesh;
    Cube_White_0001: THREE.Mesh;
    Cylinder396_brown_0: THREE.Mesh;
    Cylinder397_brown_0: THREE.Mesh;
    Cylinder398_brown_0: THREE.Mesh;
    Cylinder399_black_0: THREE.Mesh;
    Cylinder400_black_0: THREE.Mesh;
    Cylinder400_L_yellow_0: THREE.Mesh;
    Cylinder400_white_0: THREE.Mesh;
    Rectangle001_black_0: THREE.Mesh;
    pCube1_Flat_Wood_1_0: THREE.Mesh;
    pCube2_Flat_Wood_1_0: THREE.Mesh;
    pCube3_Flat_Wood_1_0: THREE.Mesh;
    pCube4_Flat_Wood_1_0: THREE.Mesh;
    pCylinder1_Flat_Wood_1_0: THREE.Mesh;
    Phone: THREE.Mesh;
    Floor: THREE.Mesh;
    ['Monitor+box']: THREE.Mesh;
    Keyboard: THREE.Mesh;
    Mouse: THREE.Mesh;
    screen: THREE.Mesh;
    Foot_right_front: THREE.Mesh;
    Foot_right_back: THREE.Mesh;
    Foot_left_front: THREE.Mesh;
    Foot_left_back: THREE.Mesh;
    Desk_plot: THREE.Mesh;
    Frame: THREE.Mesh;
    pic: THREE.Mesh;
  };
  materials: {
    RubberDuckBeak: THREE.MeshStandardMaterial;
    RubberDuck: THREE.MeshStandardMaterial;
    RubberDuckEyeBlack: THREE.MeshStandardMaterial;
    RubberDuckEyeWhite: THREE.MeshStandardMaterial;
    ['lambert1.001']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['Material.008']: THREE.MeshStandardMaterial;
    ['Material.009']: THREE.MeshStandardMaterial;
    ['Material.010']: THREE.MeshStandardMaterial;
    ['Material.011']: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
    Blue: THREE.MeshStandardMaterial;
    Green: THREE.MeshStandardMaterial;
    Orange: THREE.MeshStandardMaterial;
    ['material.001']: THREE.MeshStandardMaterial;
    ['White.001']: THREE.MeshStandardMaterial;
    Yellow: THREE.MeshStandardMaterial;
    ['Material.013']: THREE.MeshStandardMaterial;
    PRETOl: THREE.MeshStandardMaterial;
    branco1: THREE.MeshStandardMaterial;
    BookColor: THREE.MeshStandardMaterial;
    ['White.002']: THREE.MeshStandardMaterial;
    brown: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    L_yellow: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    Flat_Wood_1: THREE.MeshStandardMaterial;
    Mat: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    screen: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    pic: THREE.MeshStandardMaterial;
  };
};

type ActionName = 'CameraAction.001';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model({ scroll, ...props }: { scroll: any; setHaveAssetsLoaded: Dispatch<SetStateAction<boolean>> }) {
  const group = useRef<any>();
  const { nodes, materials, animations } = useGLTF('/desk1.glb') as GLTFResult;
  const { actions } = useAnimations<any>(animations, group);

  React.useEffect(() => {
    props.setHaveAssetsLoaded(true)
  }, [])

  React.useEffect(() => {
    if (!actions['CameraAction.001']) return;
    actions['CameraAction.001'].play().paused = true;
  }, []);

  useFrame((state) => {
    if (!actions['CameraAction.001']) return;
    actions['CameraAction.001'].time = THREE.MathUtils.lerp(
      actions['CameraAction.001'].time,
      actions['CameraAction.001'].getClip().duration * scroll.current,
      0.05
    );
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Duck"
          position={[-0.81, 2.39, -0.64]}
          rotation={[-Math.PI / 2, 0, 0.41]}
          scale={0.1}
        >
          <group
            name="483c0a06b766418d8253066e0b57992cfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode">
              <group
                name="RubberDuckBeak"
                position={[144.44, 197.95, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={129.89}
              >
                <mesh
                  name="RubberDuckBeak_RubberDuckBeak_0"
                  geometry={nodes.RubberDuckBeak_RubberDuckBeak_0.geometry}
                  material={materials.RubberDuckBeak}
                />
              </group>
              <group
                name="RubberDuckBody"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  name="RubberDuckBody_RubberDuck_0"
                  geometry={nodes.RubberDuckBody_RubberDuck_0.geometry}
                  material={materials.RubberDuck}
                />
              </group>
              <group
                name="RubberDuckEyes"
                position={[153.03, 193.69, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={129.89}
              >
                <mesh
                  name="RubberDuckEyes_RubberDuckEyeBlack_0"
                  geometry={nodes.RubberDuckEyes_RubberDuckEyeBlack_0.geometry}
                  material={materials.RubberDuckEyeBlack}
                />
                <mesh
                  name="RubberDuckEyes_RubberDuckEyeWhite_0"
                  geometry={nodes.RubberDuckEyes_RubberDuckEyeWhite_0.geometry}
                  material={materials.RubberDuckEyeWhite}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Lamp"
          position={[0.84, 3.26, -2.89]}
          rotation={[-Math.PI / 2, 0, -0.18]}
          scale={1.35}
        >
          <group
            name="cae427b5b0c74450af521d8f26bd8717fbx"
            rotation={[Math.PI / 2, -0.18, 0]}
            scale={0.01}
          >
            <group name="RootNode001" rotation={[0, -0.18, 0]}>
              <group
                name="Lamp001"
                position={[58.91, 0, -26.62]}
                rotation={[0, -0.18, 0]}
              >
                <mesh
                  name="Lamp_lambert1_0"
                  geometry={nodes.Lamp_lambert1_0.geometry}
                  material={materials['lambert1.001']}
                  position={[-28.66, 0, -33.97]}
                  rotation={[0, 0.04, 0]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Paper"
          position={[0.75, 2.34, -2.2]}
          rotation={[-Math.PI / 2, 0, 1.96]}
          scale={0.02}
        >
          <group name="Pencil&paperobjcleanermaterialmergergles">
            <mesh
              name="Object_2"
              geometry={nodes.Object_2.geometry}
              material={materials['Material.001']}
            />
            <mesh
              name="Object_3"
              geometry={nodes.Object_3.geometry}
              material={materials['Material.006']}
            />
            <mesh
              name="Object_4001"
              geometry={nodes.Object_4001.geometry}
              material={materials['Material.007']}
            />
            <mesh
              name="Object_5"
              geometry={nodes.Object_5.geometry}
              material={materials['Material.008']}
            />
            <mesh
              name="Object_6001"
              geometry={nodes.Object_6001.geometry}
              material={materials['Material.009']}
            />
            <mesh
              name="Object_7001"
              geometry={nodes.Object_7001.geometry}
              material={materials['Material.010']}
            />
            <mesh
              name="Object_8001"
              geometry={nodes.Object_8001.geometry}
              material={materials['Material.011']}
            />
          </group>
        </group>
        <group
          name="Rubik's"
          position={[-0.26, 2.29, -2.54]}
          rotation={[-Math.PI / 2, 0, 0.35]}
          scale={0.13}
        >
          <group
            name="04b925803a5c41b6bec0535a75534c03fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode004">
              <group
                name="CINEMA_4D_Editor"
                position={[818.19, 536.56, -810.92]}
                rotation={[-Math.PI, -0.79, 2.86]}
              >
                <group name="Object_4002" />
              </group>
              <group name="Cube_1" position={[0, 138.73, 19.11]}>
                <mesh
                  name="Cube_Black_0"
                  geometry={nodes.Cube_Black_0.geometry}
                  material={materials.Black}
                />
                <mesh
                  name="Cube_Blue_0"
                  geometry={nodes.Cube_Blue_0.geometry}
                  material={materials.Blue}
                />
                <mesh
                  name="Cube_Green_0"
                  geometry={nodes.Cube_Green_0.geometry}
                  material={materials.Green}
                />
                <mesh
                  name="Cube_Orange_0"
                  geometry={nodes.Cube_Orange_0.geometry}
                  material={materials.Orange}
                />
                <mesh
                  name="Cube_Red_0"
                  geometry={nodes.Cube_Red_0.geometry}
                  material={materials['material.001']}
                />
                <mesh
                  name="Cube_White_0"
                  geometry={nodes.Cube_White_0.geometry}
                  material={materials['White.001']}
                />
                <mesh
                  name="Cube_Yellow_0"
                  geometry={nodes.Cube_Yellow_0.geometry}
                  material={materials.Yellow}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Coffee"
          position={[0, 2.33, 1.9]}
          rotation={[-Math.PI / 2, 0, -0.26]}
          scale={0.11}
        >
          <group name="root001" rotation={[0, 0, 0.57]}>
            <group
              name="GLTF_SceneRootNode001"
              rotation={[Math.PI / 2, 0.57, 0]}
            >
              <group
                name="Circle001_1"
                position={[0.08, 2.17, 0.65]}
                rotation={[-0.01, -0.89, -0.04]}
                scale={0.99}
              >
                <mesh
                  name="Object_6002"
                  geometry={nodes.Object_6002.geometry}
                  material={materials['Material.013']}
                  rotation={[-0.02, 0.57, 0.01]}
                />
              </group>
              <group
                name="Circle002_4"
                position={[0.06, 0, 0.57]}
                rotation={[-0.01, -0.89, -0.04]}
              >
                <mesh
                  name="Object_8002"
                  geometry={nodes.Object_8002.geometry}
                  material={materials.PRETOl}
                  rotation={[-0.02, 0.57, 0.01]}
                />
              </group>
              <group
                name="Circle_0"
                position={[0.06, 0, 0.57]}
                rotation={[-0.01, -0.89, -0.04]}
              >
                <mesh
                  name="Object_4003"
                  geometry={nodes.Object_4003.geometry}
                  material={materials.branco1}
                  rotation={[-0.02, 0.57, 0.01]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Book"
          position={[0.51, 2.43, -3.03]}
          rotation={[-3.14, -1.28, 1.57]}
          scale={13.97}
        >
          <group
            name="9bc346a45f184a7a83092be98df11f16fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode002">
              <group
                name="Cube001"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.59, 2.18, 2.96]}
              >
                <mesh
                  name="Cube_BookColor_0"
                  geometry={nodes.Cube_BookColor_0.geometry}
                  material={materials.BookColor}
                />
                <mesh
                  name="Cube_White_0001"
                  geometry={nodes.Cube_White_0001.geometry}
                  material={materials['White.002']}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Floor_lamp"
          position={[-1.75, 0, 2.42]}
          rotation={[-Math.PI / 2, 0, -2.5]}
          scale={0.04}
        >
          <group
            name="0d260890ca704d15bb1b97ee3b579bf9fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="RootNode003">
              <group
                name="Group018"
                position={[39.4, 0, -30.87]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <group
                  name="Cylinder396"
                  position={[4.78, 0, 0]}
                  rotation={[0, -0.17, 0]}
                >
                  <group name="Object_22" position={[22.14, 0, -3.69]}>
                    <mesh
                      name="Cylinder396_brown_0"
                      geometry={nodes.Cylinder396_brown_0.geometry}
                      material={materials.brown}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder397"
                  position={[4.4, -0.22, 0]}
                  rotation={[-0.15, 0.09, -2.09]}
                >
                  <group name="Object_5001" position={[22.14, 0, -3.69]}>
                    <mesh
                      name="Cylinder397_brown_0"
                      geometry={nodes.Cylinder397_brown_0.geometry}
                      material={materials.brown}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder398"
                  position={[4.4, 0.22, 0]}
                  rotation={[0.15, 0.09, 2.09]}
                >
                  <group name="Object_8" position={[22.14, 0, -3.69]}>
                    <mesh
                      name="Cylinder398_brown_0"
                      geometry={nodes.Cylinder398_brown_0.geometry}
                      material={materials.brown}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder399"
                  position={[4.55, -0.02, 0]}
                  scale={[0.45, 0.45, 1]}
                >
                  <group name="Object_11" position={[0, 0, 116.96]}>
                    <mesh
                      name="Cylinder399_black_0"
                      geometry={nodes.Cylinder399_black_0.geometry}
                      material={materials.black}
                    />
                  </group>
                </group>
                <group
                  name="Cylinder400"
                  position={[4.55, 2.23, 0]}
                  rotation={[Math.PI / 2, 0, Math.PI / 6]}
                >
                  <group name="Object_14" position={[69.31, 120.05, 0]}>
                    <mesh
                      name="Cylinder400_black_0"
                      geometry={nodes.Cylinder400_black_0.geometry}
                      material={materials.black}
                    />
                    <mesh
                      name="Cylinder400_L_yellow_0"
                      geometry={nodes.Cylinder400_L_yellow_0.geometry}
                      material={materials.L_yellow}
                    />
                    <mesh
                      name="Cylinder400_white_0"
                      geometry={nodes.Cylinder400_white_0.geometry}
                      material={materials.white}
                    />
                  </group>
                </group>
                <group
                  name="Rectangle001"
                  position={[4.54, -0.05, 0]}
                  rotation={[0, -1.57, 0]}
                >
                  <group name="Object_19" position={[133.67, 0, 0]}>
                    <mesh
                      name="Rectangle001_black_0"
                      geometry={nodes.Rectangle001_black_0.geometry}
                      material={materials.black}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="Stol"
          position={[1.48, 0.2, 0.91]}
          rotation={[-Math.PI / 2, 0, -1.44]}
          scale={0.25}
        >
          <group
            name="554bbf20a1474905be64fffea9aedc46fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="RootNode005">
              <group
                name="pCube1"
                position={[-0.99, 2.4, -1.22]}
                scale={[0.61, 5.13, 0.61]}
              >
                <mesh
                  name="pCube1_Flat_Wood_1_0"
                  geometry={nodes.pCube1_Flat_Wood_1_0.geometry}
                  material={materials.Flat_Wood_1}
                />
              </group>
              <group
                name="pCube2"
                position={[-1.41, 2.52, 1.37]}
                rotation={[0, 0.1, 0]}
                scale={[0.61, 5.13, 0.61]}
              >
                <mesh
                  name="pCube2_Flat_Wood_1_0"
                  geometry={nodes.pCube2_Flat_Wood_1_0.geometry}
                  material={materials.Flat_Wood_1}
                />
              </group>
              <group
                name="pCube3"
                position={[1.31, 2.52, 1.6]}
                rotation={[0, 0.13, 0]}
                scale={[0.61, 5.13, 0.61]}
              >
                <mesh
                  name="pCube3_Flat_Wood_1_0"
                  geometry={nodes.pCube3_Flat_Wood_1_0.geometry}
                  material={materials.Flat_Wood_1}
                />
              </group>
              <group
                name="pCube4"
                position={[1.33, 2.52, -1.31]}
                rotation={[0, -0.1, 0]}
                scale={[0.61, 5.13, 0.61]}
              >
                <mesh
                  name="pCube4_Flat_Wood_1_0"
                  geometry={nodes.pCube4_Flat_Wood_1_0.geometry}
                  material={materials.Flat_Wood_1}
                />
              </group>
              <group
                name="pCylinder1"
                position={[0, 5.16, 0]}
                scale={[2.88, 0.14, 2.88]}
              >
                <mesh
                  name="pCylinder1_Flat_Wood_1_0"
                  geometry={nodes.pCylinder1_Flat_Wood_1_0.geometry}
                  material={materials.Flat_Wood_1}
                />
              </group>
            </group>
          </group>
        </group>
        <PerspectiveCamera
          name="Camera"
          makeDefault={true}
          far={1000}
          near={0.1}
          fov={60.1}
          position={[9.67, 4.32, -0.24]}
          rotation={[-1.42, 1.39, 1.41]}
          scale={[0.96, 1, 1]}
        />
        <pointLight
          name="Desk_lamop"
          intensity={1.134}
          decay={2}
          color="#00a5ff"
          position={[-0.42, 3.49, -2.78]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <spotLight
          name="Point"
          intensity={1}
          angle={0.98}
          penumbra={0.15}
          decay={2}
          color="#ff0000"
          position={[-1.83, 5.2, 3.8]}
          rotation={[-0.87, -0.8, 0.31]}
        >
          <group position={[0, 0, -1]} />
        </spotLight>
        <pointLight
          name="Point001_1"
          intensity={1.5}
          decay={2}
          color="#ff9500"
          position={[1.14, 5.04, 0.2]}
          rotation={[-1.72, 1.02, 0.12]}
        />
        <pointLight
          name="Point002_1"
          intensity={1.22}
          decay={2}
          color="#0004ff"
          position={[-0.97, 4.99, -3.06]}
          rotation={[-1.72, 1.02, 0.12]}
        />
        <pointLight
          name="Spot"
          intensity={0.425}
          decay={2}
          color="#ffc000"
          position={[9.39, 7.38, 3.12]}
          rotation={[-1.03, 1.15, -0.59]}
        />
        <pointLight
          name="Point003_1"
          intensity={0.40}
          decay={2}
          position={[-0.51, 2.74, -1.04]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Phone"
          geometry={nodes.Phone.geometry}
          material={materials.Mat}
          position={[-0.81, 2.33, -1.94]}
          scale={0.01}
        />
        <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          material={materials['Material.002']}
          position={[0.69, 0.22, 0.13]}
          scale={25.64}
        />
        <mesh
          name="Monitor+box"
          geometry={nodes['Monitor+box'].geometry}
          material={materials.Material}
          position={[-0.17, 0, 1.05]}
        />
        <mesh
          name="Keyboard"
          geometry={nodes.Keyboard.geometry}
          material={materials.Material}
          position={[0, 0, 1.05]}
        />
        <mesh
          name="Mouse"
          geometry={nodes.Mouse.geometry}
          material={materials.Material}
          position={[0, 0, 1.05]}
        />
        <mesh
          name="screen"
          geometry={nodes.screen.geometry}
          material={materials.screen}
          position={[-0.62, 3.37, 0.85]}
          rotation={[Math.PI / 2, 0, -1.57]}
          scale={[1.22, 1.05, 1.01]}
        />
        <mesh
          name="Foot_right_front"
          geometry={nodes.Foot_right_front.geometry}
          material={materials.Material}
          position={[0.2, 0, -1]}
        />
        <mesh
          name="Foot_right_back"
          geometry={nodes.Foot_right_back.geometry}
          material={materials.Material}
          position={[-0.2, 0, -1]}
        />
        <mesh
          name="Foot_left_front"
          geometry={nodes.Foot_left_front.geometry}
          material={materials.Material}
          position={[0.2, 0, 1]}
        />
        <mesh
          name="Foot_left_back"
          geometry={nodes.Foot_left_back.geometry}
          material={materials.Material}
          position={[-0.2, 0, 1]}
        />
        <mesh
          name="Desk_plot"
          geometry={nodes.Desk_plot.geometry}
          material={materials['Material.003']}
          position={[-0.09, 2.21, -0.06]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1.4, -0.13, -3.69]}
        />
        <mesh
          name="Frame"
          geometry={nodes.Frame.geometry}
          material={materials.Material}
          position={[0, 0, 1.05]}
        />
        <mesh
          name="pic"
          geometry={nodes.pic.geometry}
          material={materials.pic}
          position={[-0.65, 2.68, -1.12]}
          rotation={[1.51, 0.16, -1.21]}
          scale={0.55}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/desk1.glb');
